-- ==============================================================================
-- Migration: Multi-Source Price Discrepancies & Conflict Review System
-- Enables tracking, auditing, and admin resolution when different data sources
-- (HARTI, CRAN vegetablesSriLanka, CBSL, DCS, Dambulla DEC) report varying prices.
-- ==============================================================================

-- 1. Expand allowed sources on price_entries
ALTER TABLE public.price_entries DROP CONSTRAINT IF EXISTS price_entries_source_check;
ALTER TABLE public.price_entries ADD CONSTRAINT price_entries_source_check 
    CHECK (source IN ('harti', 'dambulla_dec', 'cbsl', 'dcs_retail', 'cran_vegetables_lk', 'manual'));

-- 2. Create the Price Discrepancies Table for Admin Review
CREATE TABLE IF NOT EXISTS public.price_discrepancies (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    vegetable_id TEXT NOT NULL REFERENCES public.vegetables(id) ON DELETE CASCADE,
    market_id TEXT NOT NULL REFERENCES public.markets(id) ON DELETE CASCADE,
    date DATE NOT NULL,
    price_type TEXT NOT NULL DEFAULT 'wholesale' CHECK (price_type IN ('wholesale', 'retail')),
    
    existing_price NUMERIC NOT NULL,
    existing_source TEXT NOT NULL,
    
    conflicting_price NUMERIC NOT NULL,
    conflicting_source TEXT NOT NULL,
    
    price_diff NUMERIC GENERATED ALWAYS AS (ABS(conflicting_price - existing_price)) STORED,
    diff_percent NUMERIC GENERATED ALWAYS AS (
        ROUND(ABS(conflicting_price - existing_price) / NULLIF(existing_price, 0) * 100, 2)
    ) STORED,
    
    status TEXT NOT NULL DEFAULT 'pending' 
        CHECK (status IN ('pending', 'accepted_existing', 'accepted_conflicting', 'averaged', 'dismissed')),
    resolved_price NUMERIC,
    resolved_by TEXT,
    resolved_at TIMESTAMPTZ,
    admin_notes TEXT,
    created_at TIMESTAMPTZ DEFAULT NOW(),
    
    CONSTRAINT unique_discrepancy UNIQUE (vegetable_id, market_id, date, price_type, conflicting_source)
);

-- Fast Indexing for Admin Dashboard Filtering
CREATE INDEX IF NOT EXISTS idx_discrepancies_status ON public.price_discrepancies (status, date DESC);
CREATE INDEX IF NOT EXISTS idx_discrepancies_diff ON public.price_discrepancies (diff_percent DESC);
CREATE INDEX IF NOT EXISTS idx_discrepancies_lookup ON public.price_discrepancies (vegetable_id, market_id, date);

-- Enable Row Level Security
ALTER TABLE public.price_discrepancies ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Allow public read access to price discrepancies"
    ON public.price_discrepancies FOR SELECT USING (true);

CREATE POLICY "Allow service role full access to price discrepancies"
    ON public.price_discrepancies FOR ALL USING (true) WITH CHECK (true);
