-- ==============================================================================
-- NAMIS - NATIONAL AGRICULTURAL MARKET INFORMATION SYSTEM
-- COMPLETE DATABASE RECOVERY & RECREATION SCHEMA SCRIPT
-- ==============================================================================
-- If your database was ever dropped, wiped, or newly created in Supabase,
-- paste this ENTIRE script into the Supabase SQL Editor and click "RUN".
-- It creates all tables, primary keys, foreign keys (with cascading deletes),
-- unique indexes, performance indexes, and seeds all categories, markets, and vegetables.
-- ==============================================================================

-- 1. EXTENSIONS
CREATE EXTENSION IF NOT EXISTS "uuid-ossp";

-- 2. CORE REFERENCE TABLES

-- CATEGORIES
CREATE TABLE IF NOT EXISTS public.categories (
    id TEXT PRIMARY KEY,
    name TEXT NOT NULL,
    name_si TEXT DEFAULT '',
    emoji TEXT DEFAULT '📁'
);

-- MARKETS (12 Canonical National Economic Centers & Markets)
CREATE TABLE IF NOT EXISTS public.markets (
    id TEXT PRIMARY KEY,
    name TEXT NOT NULL,
    name_si TEXT DEFAULT '',
    district TEXT DEFAULT '',
    emoji TEXT DEFAULT '🏢'
);

-- VEGETABLES & COMMODITIES (100 Canonical Items)
CREATE TABLE IF NOT EXISTS public.vegetables (
    id TEXT PRIMARY KEY,
    category_id TEXT NOT NULL REFERENCES public.categories(id) ON DELETE CASCADE,
    name TEXT NOT NULL,
    name_si TEXT DEFAULT '',
    emoji TEXT DEFAULT '🥬',
    unit TEXT DEFAULT 'kg',
    min_price NUMERIC,
    max_price NUMERIC
);

-- 3. TRANSACTIONAL & TIME-SERIES TABLES

-- PRICE ENTRIES (Main Daily Wholesale Price Time-Series)
CREATE TABLE IF NOT EXISTS public.price_entries (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    market_id TEXT NOT NULL REFERENCES public.markets(id) ON DELETE CASCADE,
    vegetable_id TEXT NOT NULL REFERENCES public.vegetables(id) ON DELETE CASCADE,
    price NUMERIC NOT NULL,
    date DATE NOT NULL,
    note TEXT,
    CONSTRAINT unique_price_entry UNIQUE (vegetable_id, market_id, date)
);

-- Indexes for lightning-fast frontend chart queries and time-series aggregations
CREATE INDEX IF NOT EXISTS idx_price_entries_date ON public.price_entries (date DESC);
CREATE INDEX IF NOT EXISTS idx_price_entries_market_date ON public.price_entries (market_id, date DESC);
CREATE INDEX IF NOT EXISTS idx_price_entries_veg_date ON public.price_entries (vegetable_id, date DESC);
CREATE INDEX IF NOT EXISTS idx_price_entries_lookup ON public.price_entries (vegetable_id, market_id, date);

-- MARKET CALENDAR (Trading days, Poya holidays, Lockdowns, Closures for ML)
CREATE TABLE IF NOT EXISTS public.market_calendar (
    date DATE PRIMARY KEY,
    is_trading_day BOOLEAN NOT NULL DEFAULT true,
    day_of_week TEXT NOT NULL,
    closure_reason TEXT,
    holiday_name TEXT,
    notes TEXT,
    created_at TIMESTAMPTZ DEFAULT NOW()
);

CREATE INDEX IF NOT EXISTS idx_market_calendar_trading ON public.market_calendar (is_trading_day);

-- 4. NEW SOURCES (Grade B+ Onward: DCS Retail & Central Bank CBSL)

-- RETAIL PRICE ENTRIES (DCS Weekly Consumer Retail Dashboard)
CREATE TABLE IF NOT EXISTS public.retail_price_entries (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    commodity_code TEXT NOT NULL,
    commodity_name TEXT NOT NULL,
    category TEXT NOT NULL,
    price NUMERIC NOT NULL,
    date_label TEXT NOT NULL,
    parsed_date DATE,
    created_at TIMESTAMPTZ DEFAULT NOW(),
    CONSTRAINT unique_retail_price UNIQUE (commodity_code, date_label)
);

CREATE INDEX IF NOT EXISTS idx_retail_prices_date ON public.retail_price_entries (parsed_date DESC);

-- CBSL PRICE ENTRIES (Central Bank Daily Economic Price Reports)
CREATE TABLE IF NOT EXISTS public.cbsl_price_entries (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    date DATE NOT NULL,
    item_name TEXT NOT NULL,
    category TEXT NOT NULL,
    pettah_wholesale NUMERIC,
    pettah_retail NUMERIC,
    dambulla_wholesale NUMERIC,
    narahenpita_retail NUMERIC,
    created_at TIMESTAMPTZ DEFAULT NOW(),
    CONSTRAINT unique_cbsl_entry UNIQUE (date, item_name)
);

CREATE INDEX IF NOT EXISTS idx_cbsl_prices_date ON public.cbsl_price_entries (date DESC);

-- 5. ADMINISTRATIVE & USER TABLES

-- ADMINS
CREATE TABLE IF NOT EXISTS public.admins (
    id TEXT PRIMARY KEY,
    email TEXT UNIQUE NOT NULL,
    password_hash TEXT NOT NULL,
    name TEXT NOT NULL,
    role TEXT DEFAULT 'viewer',
    market_id TEXT REFERENCES public.markets(id) ON DELETE SET NULL,
    created_at TIMESTAMPTZ DEFAULT NOW(),
    last_login TIMESTAMPTZ,
    is_active BOOLEAN DEFAULT true
);

-- CONTACT MESSAGES
CREATE TABLE IF NOT EXISTS public.contact_messages (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    full_name TEXT NOT NULL,
    email TEXT NOT NULL,
    phone TEXT,
    subject TEXT NOT NULL,
    message TEXT NOT NULL,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

-- SUPPORT TICKETS
CREATE TABLE IF NOT EXISTS public.support_tickets (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    ticket_id TEXT UNIQUE NOT NULL,
    phone_or_email TEXT NOT NULL,
    category TEXT NOT NULL,
    subject TEXT NOT NULL,
    priority TEXT NOT NULL,
    description TEXT NOT NULL,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

-- ==============================================================================
-- 6. SEED DATA INSERTION (ON CONFLICT DO UPDATE / NOTHING)
-- ==============================================================================

-- SEED CATEGORIES (13 Canonical Categories)
INSERT INTO public.categories (id, name, name_si, emoji) VALUES
('banana', 'Banana', 'කෙසෙල්', '🍌'),
('big-onion', 'Big Onion', 'ලොකු ළූණු', '🧅'),
('consumption-item', 'Consumption Item', 'පාරිභෝගික භාණ්ඩ', '🛒'),
('dried-chillies', 'Dried Chillies', 'වියළි මිරිස්', '🌶️'),
('eggs', 'Eggs', 'බිත්තර', '🥚'),
('imported-rice', 'Imported Rice', 'ආනයනික සහල්', '🍚'),
('low-country-vegetable', 'Low country Vegetable', 'පහතරට එළවළු', '🥒'),
('onion', 'Onion', 'ළූණු', '🧅'),
('other-fruits--rs-fruit-', 'Other Fruits (Rs/Fruit)', 'වෙනත් පලතුරු', '🍎'),
('potatoes', 'Potatoes', 'අර්තාපල්', '🥔'),
('pulses', 'Pulses', 'ධාන්‍ය / පරිප්පු', '🌾'),
('rice', 'Rice', 'සහල්', '🌾'),
('up-country-vegetable', 'Up Country Vegetable', 'උඩරට එළවළු', '🥕')
ON CONFLICT (id) DO UPDATE SET name = EXCLUDED.name, emoji = EXCLUDED.emoji;

-- SEED MARKETS (12 Canonical Dedicated Economic Centres)
INSERT INTO public.markets (id, name, name_si, district, emoji) VALUES
('bandarawela', 'Bandarawela Economic Center', 'බණ්ඩාරවෙල ආර්ථික මධ්‍යස්ථානය', 'Badulla', '🏢'),
('dambulla', 'Dambulla Economic Center', 'දඹුල්ල ආර්ථික මධ්‍යස්ථානය', 'Matale', '🏢'),
('kandy', 'Kandy Central Market', 'මහනුවර වෙළෙඳපොළ', 'Kandy', '🏢'),
('keppetipola', 'Keppetipola Economic Center', 'කැප්පෙටිපොළ ආර්ථික මධ්‍යස්ථානය', 'Badulla', '🏢'),
('manning', 'Manning Market (Peliyagoda)', 'මැනිං වෙළෙඳපොළ', 'Colombo', '🏢'),
('meegoda', 'Meegoda Economic Center', 'මීගොඩ ආර්ථික මධ්‍යස්ථානය', 'Colombo', '🏢'),
('norochchole', 'Norochchole Economic Center', 'නොරොච්චෝලේ ආර්ථික මධ්‍යස්ථානය', 'Puttalam', '🏢'),
('nuwara-eliya', 'Nuwara Eliya Economic Center', 'නුවරඑළිය ආර්ථික මධ්‍යස්ථානය', 'Nuwara Eliya', '🏢'),
('peliyagoda', 'Peliyagoda Economic Center', 'පෑලියගොඩ ආර්ථික මධ්‍යස්ථානය', 'Gampaha', '🏢'),
('pettah', 'Pettah Wholesale Market', 'පිටකොටුව තොග වෙළෙඳපොළ', 'Colombo', '🏢'),
('thambuththegama', 'Thambuththegama Economic Center', 'තඹුත්තේගම ආර්ථික මධ්‍යස්ථානය', 'Anuradhapura', '🏢'),
('veyangoda', 'Veyangoda Economic Center', 'වේයන්ගොඩ ආර්ථික මධ්‍යස්ථානය', 'Gampaha', '🏢')
ON CONFLICT (id) DO UPDATE SET name = EXCLUDED.name, district = EXCLUDED.district;

-- SEED VEGETABLES (100 Canonical Items)
INSERT INTO public.vegetables (id, category_id, name, name_si, emoji, unit) VALUES
('ambul', 'banana', 'Ambul', 'ඇඹුල්', '🍌', 'kg'),
('ambul-rs-kg-', 'banana', 'Ambul(Rs/Kg)', 'ඇඹුල් (කි.ග්‍රෑ)', '🍌', 'kg'),
('anamalu--rs-fruits-', 'banana', 'Anamalu (Rs/Fruits)', 'ආනමාලු', '🍌', 'kg'),
('kolikuttu', 'banana', 'Kolikuttu', 'කෝලිකුට්ටු', '🍌', 'kg'),
('kolikuttu--rs-fruits-', 'banana', 'Kolikuttu (Rs/Fruits)', 'කෝලිකුට්ටු (ගෙඩි)', '🍌', 'kg'),
('papaya', 'banana', 'Papaya', 'පැපොල්', '🍈', 'kg'),
('papaya--rs-kg-', 'banana', 'Papaya (Rs/Kg)', 'පැපොල් (කි.ග්‍රෑ)', '🍈', 'kg'),
('passion-fruits', 'banana', 'Passion Fruits', 'පැෂන් ෆෘට්', '🍈', 'kg'),
('seeni', 'banana', 'Seeni', 'සීනි කෙසෙල්', '🍌', 'kg'),
('imported', 'big-onion', 'Imported', 'ආනයනික ලොකු ළූණු', '🧅', 'kg'),
('sugar-white-', 'consumption-item', 'Sugar(White)', 'සුදු සීනි', '🍚', 'Rs/Kg'),
('wheat-flour', 'consumption-item', 'Wheat Flour', 'තිරිඟු පිටි', '🌾', 'Rs/Kg'),
('-', 'eggs', '.', '.', '🥚', 'Rs/Egg'),
('brown', 'eggs', 'Brown', 'දුඹුරු බිත්තර', '🥚', 'Rs/Egg'),
('d-a-t-a-m-anagement-division', 'eggs', 'D a t a M anagement Division', '', '🥚', 'Rs/Egg'),
('i-n-f-o-r-m-a-t-i-o-n-d-i-v-i-s-i-o-n', 'eggs', 'I n f o r m a t i o n D i v i s i o n', '', '🥚', 'Rs/Egg'),
('i-n-f-ormation-division', 'eggs', 'I n f ormation Division', '', '🥚', 'Rs/Egg'),
('information-division', 'eggs', 'Information Division', '', '🥚', 'Rs/Egg'),
('white', 'eggs', 'White', 'සුදු බිත්තර', '🥚', 'Rs/Egg'),
('kiri-ponne-pall-ponne-', 'imported-rice', 'Kiri Ponne(Pall Ponne)', 'කිරි පොන්නි', '🍚', 'kg'),
('kora', 'imported-rice', 'Kora', 'කෝරා', '🍚', 'kg'),
('ponne-1', 'imported-rice', 'Ponne 1', 'පොන්නි 1', '🍚', 'kg'),
('ponne-samba', 'imported-rice', 'Ponne Samba', 'පොන්නි සම්බා', '🍚', 'kg'),
('raw-white', 'imported-rice', 'Raw White', 'කැකුළු සුදු', '🍚', 'kg'),
('samba-ponne-1', 'imported-rice', 'Samba Ponne 1', 'සම්බා පොන්නි 1', '🍚', 'kg'),
('ash-plantains', 'low-country-vegetable', 'Ash Plantains', 'අළු කෙසෙල්', '🍌', 'kg'),
('b-onion-imported', 'low-country-vegetable', 'B''Onion Imported', 'ආනයනික ලොකු ළූණු', '🧅', 'kg'),
('b-onion-imported-', 'low-country-vegetable', 'B''Onion(Imported)', 'ආනයනික ලොකු ළූණු', '🧅', 'kg'),
('bitter-gourd', 'low-country-vegetable', 'Bitter Gourd', 'කරවිල', '🥒', 'kg'),
('bitter-gourd--other-', 'low-country-vegetable', 'Bitter Gourd (Other)', 'කරවිල (වෙනත්)', '🥒', 'kg'),
('bitter-gourd--villag', 'low-country-vegetable', 'Bitter Gourd (Villag', 'ගම් කරවිල', '🥒', 'kg'),
('bitter-gourd--village', 'low-country-vegetable', 'Bitter Gourd (Village', 'ගම් කරවිල', '🥒', 'kg'),
('bitter-gourd--village-', 'low-country-vegetable', 'Bitter Gourd (Village)', 'ගම් කරවිල', '🥒', 'kg'),
('black-gram', 'low-country-vegetable', 'Black Gram', 'උඳු', '🌾', 'kg'),
('brinjals', 'low-country-vegetable', 'Brinjals', 'වම්බටු', '🍆', 'kg'),
('brinjals--other-', 'low-country-vegetable', 'Brinjals (Other)', 'වම්බටු (වෙනත්)', '🍆', 'kg'),
('brinjals--village-', 'low-country-vegetable', 'Brinjals (Village)', 'ගම් වම්බටු', '🍆', 'kg'),
('capsicum', 'low-country-vegetable', 'Capsicum', 'මාළු මිරිස්', '🫑', 'kg'),
('cucumber', 'low-country-vegetable', 'Cucumber', 'පිපිඤ්ඤා', '🥒', 'kg'),
('drumstick', 'low-country-vegetable', 'Drumstick', 'මුරුංගා', '🥖', 'kg'),
('eggplant', 'low-country-vegetable', 'Eggplant', 'බටු', '🍆', 'kg'),
('green-chillies', 'low-country-vegetable', 'Green Chillies', 'අමු මිරිස්', '🌶️', 'kg'),
('ladies-fingers', 'low-country-vegetable', 'Ladies Fingers', 'බණ්ඩක්කා', '🥬', 'kg'),
('lime', 'low-country-vegetable', 'Lime', 'දෙහි', '🍋', 'kg'),
('long-beans', 'low-country-vegetable', 'Long Beans', 'මෑකරල්', '🥬', 'kg'),
('luffa', 'low-country-vegetable', 'Luffa', 'වැටකොළු', '🥒', 'kg'),
('manioc', 'low-country-vegetable', 'Manioc', 'මඤ්ඤොක්කා', '🥔', 'kg'),
('potato--imported-', 'low-country-vegetable', 'Potato (Imported)', 'ආනයනික අර්තාපල්', '🥔', 'kg'),
('potato--nuwaraeliya--', 'low-country-vegetable', 'Potato (Nuwaraeliya )', 'නුවරඑළිය අර්තාපල්', '🥔', 'kg'),
('potato--nuwaraeliya-', 'low-country-vegetable', 'Potato (Nuwaraeliya)', 'නුවරඑළිය අර්තාපල්', '🥔', 'kg'),
('potato--welimada-', 'low-country-vegetable', 'Potato (Welimada)', 'වැලිමඩ අර්තාපල්', '🥔', 'kg'),
('potato-imported-', 'low-country-vegetable', 'Potato(Imported)', 'ආනයනික අර්තාපල්', '🥔', 'kg'),
('pumpkin', 'low-country-vegetable', 'Pumpkin', 'වට්ටක්කා', '🎃', 'kg'),
('snake-gourd', 'low-country-vegetable', 'Snake Gourd', 'පතෝල', '🥒', 'kg'),
('sweet-potatoe', 'low-country-vegetable', 'Sweet Potatoe', 'බතල', '🥔', 'kg'),
('imported----div-0-', 'onion', 'Imported - #DIV/0!', '', '🧅', 'Rs/Kg'),
('sinnan', 'onion', 'Sinnan', 'සින්නන් ළූණු', '🧅', 'Rs/Kg'),
('sinnan----div-0-', 'onion', 'Sinnan - #DIV/0!', '', '🧅', 'Rs/Kg'),
('vedalan', 'onion', 'Vedalan', 'වෙදලන් ළූණු', '🧅', 'Rs/Kg'),
('vedalan----div-0-', 'onion', 'Vedalan - #DIV/0!', '', '🧅', 'Rs/Kg'),
('vedalan----div-0---div-0-', 'onion', 'Vedalan - #DIV/0! #DIV/0!', '', '🧅', 'Rs/Kg'),
('avocado', 'other-fruits--rs-fruit-', 'Avocado', 'අලිගැටපේර', '🥑', 'kg'),
('karathak', 'other-fruits--rs-fruit-', 'Karathak', 'කරතක්', '🍎', 'kg'),
('orange', 'other-fruits--rs-fruit-', 'Orange', 'දොඩම්', '🍊', 'kg'),
('pineapple---large', 'other-fruits--rs-fruit-', 'Pineapple - Large', 'අන්නාසි (විශාල)', '🍍', 'kg'),
('pineapple---medium', 'other-fruits--rs-fruit-', 'Pineapple - Medium', 'අන්නාසි (මධ්‍යම)', '🍍', 'kg'),
('pineapple---small', 'other-fruits--rs-fruit-', 'Pineapple - Small', 'අන්නාසි (කුඩා)', '🍍', 'kg'),
('woodapple', 'other-fruits--rs-fruit-', 'Woodapple', 'දිවුල්', '🥥', 'kg'),
('nuwaraeliya', 'potatoes', 'Nuwaraeliya', 'නුවරඑළිය අර්තාපල්', '🥔', 'Rs/Kg'),
('welimada', 'potatoes', 'Welimada', 'වැලිමඩ අර්තාපල්', '🥔', 'Rs/Kg'),
('welimada----div-0-', 'potatoes', 'Welimada - #DIV/0!', '', '🥔', 'Rs/Kg'),
('cowpea', 'pulses', 'Cowpea', 'කවුපි', '🌾', 'Rs/Kg'),
('eggs--rs-egg---', 'pulses', 'Eggs (Rs/Egg) .', 'බිත්තර', '🥚', 'Rs/Kg'),
('green-gram', 'pulses', 'Green Gram', 'මුං ඇට', '🌾', 'Rs/Kg'),
('head', 'pulses', 'Head', '', '🌾', 'Rs/Kg'),
('marketing---food-policy-division', 'pulses', 'Marketing & Food Policy Division', '', '🌾', 'Rs/Kg'),
('red-dhal', 'pulses', 'Red Dhal', 'මයිසූර් පරිප්පු', '🌾', 'Rs/Kg'),
('imported-rice', 'rice', 'Imported Rice', 'ආනයනික සහල්', '🍚', 'Rs/kg'),
('keeri-samba', 'rice', 'Keeri Samba', 'කීරි සම්බා', '🍚', 'Rs/kg'),
('nadu', 'rice', 'Nadu', 'නාඩු', '🍚', 'Rs/kg'),
('nadu-1', 'rice', 'Nadu 1', 'නාඩු 1', '🍚', 'Rs/kg'),
('nadu-2', 'rice', 'Nadu 2', 'නාඩු 2', '🍚', 'Rs/kg'),
('raw-red', 'rice', 'Raw red', 'රතු කැකුළු', '🍚', 'Rs/kg'),
('raw-red--ref-----ref---ref-', 'rice', 'Raw red #REF! - #REF! #REF!', '', '🍚', 'Rs/50 kg'),
('samba-1', 'rice', 'Samba 1', 'සම්බා 1', '🍚', 'Rs/kg'),
('samba-1----div-0-', 'rice', 'Samba 1 - #DIV/0!', '', '🍚', 'Rs/50 kg'),
('samba-1----div-0---div-0-', 'rice', 'Samba 1 - #DIV/0! #DIV/0!', '', '🍚', 'Rs/50 kg'),
('samba-2', 'rice', 'Samba 2', 'සම්බා 2', '🍚', 'Rs/kg'),
('samba-3', 'rice', 'Samba 3', 'සම්බා 3', '🍚', 'Rs/50 kg'),
('samba-3------div-0-', 'rice', 'Samba 3 - - #DIV/0!', '', '🍚', 'Rs/50 kg'),
('beans', 'up-country-vegetable', 'Beans', 'බෝංචි', '🥬', 'kg'),
('beet-root', 'up-country-vegetable', 'Beet root', 'බීට්රූට්', '🥔', 'kg'),
('beet-root--n-eliya-', 'up-country-vegetable', 'Beet root (N Eliya)', 'බීට්රූට් (නුවරඑළිය)', '🥔', 'kg'),
('beet-root-n-eliya-', 'up-country-vegetable', 'Beet Root(N''Eliya)', 'බීට්රූට් (නුවරඑළිය)', '🥔', 'kg'),
('cabbage--kandy-', 'up-country-vegetable', 'Cabbage (Kandy)', 'ගෝවා (මහනුවර)', '🥬', 'kg'),
('carrot', 'up-country-vegetable', 'Carrot', 'කැරට්', '🥕', 'kg'),
('knolkhol', 'up-country-vegetable', 'Knolkhol', 'නෝකෝල්', '🥬', 'kg'),
('leeks', 'up-country-vegetable', 'Leeks', 'ලීක්ස්', '🥬', 'kg'),
('raddish', 'up-country-vegetable', 'Raddish', 'රාබු', '🥕', 'kg'),
('tomato', 'up-country-vegetable', 'Tomato', 'තක්කාලි', '🍅', 'kg')
ON CONFLICT (id) DO UPDATE SET name = EXCLUDED.name, unit = EXCLUDED.unit;

-- ==============================================================================
-- 7. ENABLE ROW LEVEL SECURITY (RLS) & PUBLIC READ ACCESS
-- ==============================================================================
ALTER TABLE public.categories ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.markets ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.vegetables ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.price_entries ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.market_calendar ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.retail_price_entries ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.cbsl_price_entries ENABLE ROW LEVEL SECURITY;

DO $$ BEGIN
    IF NOT EXISTS (SELECT 1 FROM pg_policies WHERE policyname = 'Public categories are viewable by everyone' AND tablename = 'categories') THEN
        CREATE POLICY "Public categories are viewable by everyone" ON public.categories FOR SELECT USING (true);
    END IF;
    IF NOT EXISTS (SELECT 1 FROM pg_policies WHERE policyname = 'Public markets are viewable by everyone' AND tablename = 'markets') THEN
        CREATE POLICY "Public markets are viewable by everyone" ON public.markets FOR SELECT USING (true);
    END IF;
    IF NOT EXISTS (SELECT 1 FROM pg_policies WHERE policyname = 'Public vegetables are viewable by everyone' AND tablename = 'vegetables') THEN
        CREATE POLICY "Public vegetables are viewable by everyone" ON public.vegetables FOR SELECT USING (true);
    END IF;
    IF NOT EXISTS (SELECT 1 FROM pg_policies WHERE policyname = 'Public price entries are viewable by everyone' AND tablename = 'price_entries') THEN
        CREATE POLICY "Public price entries are viewable by everyone" ON public.price_entries FOR SELECT USING (true);
    END IF;
    IF NOT EXISTS (SELECT 1 FROM pg_policies WHERE policyname = 'Public market calendar is viewable by everyone' AND tablename = 'market_calendar') THEN
        CREATE POLICY "Public market calendar is viewable by everyone" ON public.market_calendar FOR SELECT USING (true);
    END IF;
    IF NOT EXISTS (SELECT 1 FROM pg_policies WHERE policyname = 'Public retail price entries are viewable by everyone' AND tablename = 'retail_price_entries') THEN
        CREATE POLICY "Public retail price entries are viewable by everyone" ON public.retail_price_entries FOR SELECT USING (true);
    END IF;
    IF NOT EXISTS (SELECT 1 FROM pg_policies WHERE policyname = 'Public cbsl price entries are viewable by everyone' AND tablename = 'cbsl_price_entries') THEN
        CREATE POLICY "Public cbsl price entries are viewable by everyone" ON public.cbsl_price_entries FOR SELECT USING (true);
    END IF;
END $$;
