"""
Extract daily commodity prices from a HARTI "Wholesale Prices" PDF report.

Two kinds of tables are pulled out, wherever they appear in the PDF:
  - Rice & Subsidiary Food Crops -> Pettah market (native Range + Average)
  - Vegetables/Fruits            -> Peliyagoda market (Range only; average
    price is computed as the midpoint of the range, since the source PDF
    does not print a native average for regional markets)

Pages are NOT assumed to be at fixed indices (0/1). Some daily PDFs only
include the vegetable report, some reorder pages, some repeat an English
table followed by a Sinhala duplicate. Each page's table is inspected and
classified by its actual header content ("Item ... Pettah ..." vs
"Variety ... Peliyagoda ...") before parsing, and only the first matching
page of each kind is used. If a PDF is missing one of the two tables
entirely, that section is simply skipped and reported - the run does not
fail.

Each distinct item gets its own JSON file containing a growing list of daily
records (one record appended per PDF processed). Re-running on the same date
will not create a duplicate entry for that date.

Usage:
    python extract_pdf_prices.py <path_to_pdf> [--output-dir DIR]
"""

import argparse
import json
import re
import sys
from pathlib import Path

import pdfplumber

# ---------------------------------------------------------------------------
# Config: known section/category headers on page 1 (Rice & Subsidiary Food Crops)
# ---------------------------------------------------------------------------
PAGE1_CATEGORY_NAMES = {
    "rice",
    "imported rice",
    "dried chillies",
    "onion",
    "big onion",
    "potatoes",
    "pulses",
    "consumption item",
    "eggs",
}
PAGE1_SKIP_LINES = {"subsidiary food crops"}

# Items deliberately excluded from extraction/output, keyed by (category, item)
# exactly as they appear in the written JSON records. Add an entry here (and
# delete the corresponding JSON file once) to permanently stop tracking an
# item - process_pdf() filters these out before anything gets written, so
# they will never be regenerated by future runs.
IGNORED_ITEMS = {
    ("Dried Chillies", "Local"),  # Pettah: 0 non-null records across all 925 days tracked
    ("Imported Rice", "Raw red"),  # Pettah: 0 non-null records across all 925 days tracked
    ("Imported Rice", "Nadu"),  # Pettah: last real price 2025-05-14, appears discontinued
    ("Up Country Vegetable", "Cabbage (N'Eliya)"),  # Peliyagoda: last real price 2025-11-27, 269-day max gap
    ("Big Onion", "Local"),  # Pettah: last real price 2025-12-18, appears discontinued
    ("Low country Vegetable", "Big-onion Local"),  # Peliyagoda: last real price 2025-12-18, appears discontinued
    ("Pulses", "Cowpea (White)"),  # Pettah: only tracked 2025-07 to 2025-12, insufficient history
    ("Other Fruits (Rs/Fruit)", "Karathakolomban"),  # Peliyagoda: last real price 2025-12-22, appears discontinued
    ("Other Fruits (Rs/Fruit)", "Mango - Betti"),  # Peliyagoda: sparse (17.8% coverage), excluded per user decision
}

# The name group excludes any decimal-point number ((?!\d+\.\d+).) so a
# rare rendering glitch where a stray decimal value appears before the real
# range (e.g. "Samba 1 - 246.67 240.00 - 246.00 243.33 ...") is rejected as
# ambiguous rather than silently swallowed into the item name (which
# previously produced wrong-looking min/max values under a corrupted name).
# Such lines fall through to the no-data fallback below instead.
ITEM_LINE_RE = re.compile(
    r"^(?P<name>(?:(?!\d+\.\d+).)*?)\s*(?P<min>\d+\.\d+)\s*-\s*(?P<max>\d+\.\d+)\s+(?P<avg>\d+\.\d+)"
)
DECIMAL_RE = re.compile(r"\d+\.\d+")
RANGE_RE = re.compile(r"(\d+(?:\.\d+)?)\s*-\s*(\d+(?:\.\d+)?)")
DATE_RE = re.compile(r"(\d{4})[.\-](\d{2})[.\-](\d{2})")


def slugify(text: str) -> str:
    text = text.strip().lower()
    text = re.sub(r"[^a-z0-9]+", "_", text)
    return text.strip("_")


def strip_unit(line: str):
    """If a line is 'Name (Unit)' with nothing else after it, split them."""
    m = re.match(r"^(.*?)\s*\(([^)]*)\)\s*$", line)
    if m:
        return m.group(1).strip(), m.group(2).strip()
    return line.strip(), None


def find_date(pdf_path: Path, pdf: "pdfplumber.PDF") -> str:
    """Look for a YYYY.MM.DD / YYYY-MM-DD date, first in the filename, then in page 1 text."""
    m = DATE_RE.search(pdf_path.name)
    if not m:
        m = DATE_RE.search(pdf.pages[0].extract_text() or "")
    if not m:
        raise ValueError("Could not find a date (YYYY-MM-DD) in filename or page 1")
    y, mo, d = m.groups()
    return f"{y}-{mo}-{d}"


def classify_page(page) -> tuple:
    """Look at a page's first table and decide if it's the Pettah rice/food-crop
    table, the (English) Peliyagoda vegetable table, or neither (e.g. a chart
    page, or the Sinhala duplicate of either table). Returns (kind, table)
    where kind is 'pettah', 'peliyagoda', or None."""
    tables = page.extract_tables()
    if not tables:
        return None, None
    table = tables[0]
    if not table or not table[0]:
        return None, None

    header_cells = " ".join(str(c) for row in table[:2] for c in row if c)
    first_header_cell = (table[0][0] or "").strip()

    if first_header_cell == "Item" and "Pettah" in header_cells:
        return "pettah", table
    if first_header_cell == "Variety":
        return "peliyagoda", table
    return None, None


# ---------------------------------------------------------------------------
# Page 1: Rice & Subsidiary Food Crops (Pettah market)
# ---------------------------------------------------------------------------
def parse_pettah_page(text: str, date: str) -> list:
    records = []
    current_category = None
    current_unit = None

    for raw_line in text.splitlines():
        line = raw_line.strip()
        if not line:
            continue

        name_only, unit = strip_unit(line)

        if name_only.lower() in PAGE1_CATEGORY_NAMES:
            current_category = name_only
            current_unit = unit
            continue
        if name_only.lower() in PAGE1_SKIP_LINES:
            continue

        if current_category is None:
            # Still in the title/header block above "Rice (Rs/kg)" - ignore.
            continue

        m = ITEM_LINE_RE.match(line)
        if m:
            item_name = re.sub(r"[\s\-]+$", "", m.group("name")).strip()
            min_price = float(m.group("min"))
            max_price = float(m.group("max"))
            avg_price = float(m.group("avg"))
            records.append(
                {
                    "date": date,
                    "item": item_name,
                    "category": current_category,
                    "unit": current_unit,
                    "market": "Pettah",
                    "min_price": min_price,
                    "max_price": max_price,
                    "average_price": avg_price,
                    "average_computed": False,
                    "range": f"{min_price:.2f} - {max_price:.2f}",
                }
            )
        else:
            # No clean Pettah range/average match. This can be a genuine
            # "-" (no data) row, a row where the Marandagahamula columns
            # (which we deliberately ignore) still carry numbers even though
            # Pettah is blank, a malformed range missing its dash, or an
            # ambiguous stray-decimal-before-the-real-range glitch rejected
            # above. In all of those cases we only want the item's name -
            # truncate at the first DECIMAL number (not the first digit, so
            # a variety number like "Samba 1"/"Nadu 2" is preserved) so no
            # stray price values ever leak into the item name.
            decimal_match = DECIMAL_RE.search(line)
            item_name = line[: decimal_match.start()] if decimal_match else line
            item_name = re.sub(r"[\s\-]+$", "", item_name).strip()
            if not item_name:
                continue
            records.append(
                {
                    "date": date,
                    "item": item_name,
                    "category": current_category,
                    "unit": current_unit,
                    "market": "Pettah",
                    "min_price": None,
                    "max_price": None,
                    "average_price": None,
                    "average_computed": False,
                    "range": None,
                }
            )
    return records


# ---------------------------------------------------------------------------
# Page 2: Vegetables/Fruits (Peliyagoda market only, per user's instruction)
# ---------------------------------------------------------------------------
# The report always follows this section order; some PDFs are missing the
# "Up Country Vegetable" header row outright (replaced by a stray metadata
# row like a leftover date "21/1/2024" with no other columns filled in), so
# a plain "all other columns empty -> this is a new category" heuristic
# mis-files every item after it under that stray text. Recognize category
# rows by name instead, and default to the first section until a real one
# is seen.
VEG_CATEGORY_RE = re.compile(r"vegetable|banana|other fruit", re.IGNORECASE)

# Some item names get split/truncated differently depending on how a PDF's
# table cells happen to wrap ("Karathakolomban" mango and "Passion Fruits"
# show up as several different partial strings across different PDFs).
# Normalize known variants to one canonical name so they don't fragment into
# separate item files. "- Medium"/"- Small" are Pineapple's rows (they
# always immediately follow "Pineapple - Large" in this report) but don't
# repeat "Pineapple" in their own cell, so make that explicit too.
PELIYAGODA_NAME_ALIASES = [
    (re.compile(r"karathakol", re.IGNORECASE), "Karathakolomban"),
    (re.compile(r"passion\s*fruit", re.IGNORECASE), "Passion Fruits"),
    (re.compile(r"^medium$", re.IGNORECASE), "Pineapple - Medium"),
    (re.compile(r"^small$", re.IGNORECASE), "Pineapple - Small"),
]


def normalize_peliyagoda_name(name: str) -> str:
    name = name.strip()
    name = re.sub(r"^-+\s*", "", name)   # leading "- " list marker
    name = re.sub(r"[\s\-]+$", "", name)  # trailing stray "-"
    for pattern, canonical in PELIYAGODA_NAME_ALIASES:
        if pattern.search(name):
            return canonical
    return name


def clean_market_name(name: str, fallback_idx: int = 1) -> str:
    cleaned = re.sub(r'\d{4}[.\-/]\d{1,2}[.\-/]\d{1,2}|\d{1,2}[.\-/]\d{1,2}[.\-/]\d{4}', '', name)
    cleaned = re.sub(r'(?i)\bmarket\b|\bcenter\b|\bdec\b', '', cleaned).strip()
    c_lower = cleaned.lower()
    if 'peliyagod' in c_lower: return 'Peliyagoda'
    if 'dambulla' in c_lower: return 'Dambulla'
    if 'kandy' in c_lower: return 'Kandy'
    if 'keppetipola' in c_lower or 'kappetipola' in c_lower or 'akeppetipola' in c_lower: return 'Keppetipola'
    if 'meegoda' in c_lower or 'megoda' in c_lower: return 'Meegoda'
    if 'norochchol' in c_lower: return 'Norochchole'
    if any(k in c_lower for k in ['thambuththegam', 't\'thegama', 'hambuththegam', 'ambuththega', 't’thegama']): return 'Thambuththegama'
    if 'nuwara' in c_lower: return 'Nuwara Eliya'
    if 'bandarawela' in c_lower: return 'Bandarawela'
    if 'veyangoda' in c_lower: return 'Veyangoda'
    if 'pettah' in c_lower or 'petha' in c_lower: return 'Pettah'
    if 'manning' in c_lower: return 'Manning Market'
    sanitized = re.sub(r'[^a-zA-Z\s\-]', '', cleaned).strip()
    return sanitized if sanitized else f"Market_{fallback_idx}"


def parse_peliyagoda_page(table: list, date: str) -> list:
    records = []
    current_category = "Up Country Vegetable"

    market_names = []
    if len(table) > 1:
        num_cols = max((len(r) for r in table), default=0) - 1
        for i in range(1, num_cols + 1):
            parts = []
            if len(table[0]) > i and table[0][i]:
                parts.append(str(table[0][i]).strip())
            if len(table[1]) > i and table[1][i]:
                parts.append(str(table[1][i]).strip())
            raw_name = " ".join(parts).replace('\n', ' ')
            market_names.append(clean_market_name(raw_name, i))
    
    if not market_names:
        market_names = ["Peliyagoda"]

    for row in table[2:]:  # first 2 rows are date/market headers
        if not row or row[0] is None:
            continue
        first_cell = row[0].strip()
        if not first_cell:
            continue

        rest = row[1:]
        all_rest_empty = all((c is None or str(c).strip() in ("", "-")) for c in rest)

        if VEG_CATEGORY_RE.search(first_cell):
            current_category = first_cell
            continue

        if all_rest_empty:
            continue

        peliyagoda_cell = rest[0] if rest else None
        combined = f"{first_cell} {peliyagoda_cell or ''}".strip()
        m = RANGE_RE.search(combined)

        if m:
            item_name = normalize_peliyagoda_name(combined[: m.start()])
            min_price = float(m.group(1))
            max_price = float(m.group(2))
            avg_price = round((min_price + max_price) / 2, 2)
            records.append(
                {
                    "date": date,
                    "item": item_name,
                    "category": current_category,
                    "unit": None,
                    "market": market_names[0],
                    "min_price": min_price,
                    "max_price": max_price,
                    "average_price": avg_price,
                    "average_computed": True,
                    "range": f"{min_price:.2f} - {max_price:.2f}",
                }
            )
        else:
            item_name = normalize_peliyagoda_name(first_cell)
            records.append(
                {
                    "date": date,
                    "item": item_name,
                    "category": current_category,
                    "unit": None,
                    "market": market_names[0],
                    "min_price": None,
                    "max_price": None,
                    "average_price": None,
                    "average_computed": False,
                    "range": None,
                }
            )

        # Extract other markets
        for i, cell in enumerate(rest[1:], start=1):
            if cell is None or str(cell).strip() in ("", "-"):
                continue
            market_name = market_names[i] if i < len(market_names) else f"Market_{i+1}"
            m_other = RANGE_RE.search(str(cell))
            if m_other:
                min_p = float(m_other.group(1))
                max_p = float(m_other.group(2))
                avg_p = round((min_p + max_p) / 2, 2)
                records.append({
                    "date": date,
                    "item": item_name,
                    "category": current_category,
                    "unit": None,
                    "market": market_name,
                    "min_price": min_p,
                    "max_price": max_p,
                    "average_price": avg_p,
                    "average_computed": True,
                    "range": f"{min_p:.2f} - {max_p:.2f}",
                })

    return records


# ---------------------------------------------------------------------------
# Output: one growing JSON array per item
# ---------------------------------------------------------------------------
def write_item_json(record: dict, output_dir: Path) -> Path:
    filename = f"{slugify(record['market'])}_{slugify(record['category'])}_{slugify(record['item'])}.json"
    path = output_dir / filename

    history = []
    if path.exists() and path.stat().st_size > 0:
        with open(path, "r", encoding="utf-8") as f:
            history = json.load(f)

    # Replace any existing entry for the same date, otherwise append.
    history = [h for h in history if h.get("date") != record["date"]]
    history.append(record)
    # Newest date first (index 0 = latest price).
    history.sort(key=lambda r: r["date"], reverse=True)

    # Write atomically (temp file + rename) so a killed/interrupted process
    # can never leave this file truncated or corrupted.
    tmp_path = path.with_suffix(path.suffix + ".tmp")
    with open(tmp_path, "w", encoding="utf-8") as f:
        json.dump(history, f, indent=2, ensure_ascii=False)
    tmp_path.replace(path)

    return path


def process_pdf(pdf_path: Path, output_dir: Path) -> dict:
    """Extract Pettah + Peliyagoda prices from one PDF and write/update the
    per-item JSON files in output_dir. Returns a small stats dict.

    Scans every page (not just page 1/2) and classifies each one by its
    actual table header, so this copes with PDFs that: omit the Pettah page
    entirely, put the vegetable table first, have extra chart pages in
    between, or repeat a Sinhala duplicate of either table later on.
    """
    pdf_path = Path(pdf_path)
    output_dir = Path(output_dir)
    output_dir.mkdir(parents=True, exist_ok=True)

    pettah_records, peliyagoda_records = [], []
    pettah_page_found, peliyagoda_page_found = False, False

    with pdfplumber.open(pdf_path) as pdf:
        date = find_date(pdf_path, pdf)

        for page in pdf.pages:
            if pettah_page_found and peliyagoda_page_found:
                break  # both tables located, no need to scan remaining pages

            kind, table = classify_page(page)

            if kind == "pettah" and not pettah_page_found:
                pettah_page_found = True
                page_text = page.extract_text() or ""
                pettah_records = parse_pettah_page(page_text, date)

            elif kind == "peliyagoda" and not peliyagoda_page_found:
                peliyagoda_page_found = True
                peliyagoda_records = parse_peliyagoda_page(table, date)

    all_records = [
        r for r in (pettah_records + peliyagoda_records)
        if (r["category"], r["item"]) not in IGNORED_ITEMS
    ]
    for rec in all_records:
        write_item_json(rec, output_dir)

    with_data = sum(1 for r in all_records if r["min_price"] is not None)
    warnings = []
    if not pettah_page_found:
        warnings.append("no Pettah (Rice & Subsidiary Food Crops) table found")
    if not peliyagoda_page_found:
        warnings.append("no Peliyagoda (vegetable) table found")

    return {
        "date": date,
        "total": len(all_records),
        "with_data": with_data,
        "pettah_found": pettah_page_found,
        "peliyagoda_found": peliyagoda_page_found,
        "warnings": warnings,
        "output_dir": str(output_dir.resolve()),
    }


def main():
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("pdf_path", help="Path to the daily price PDF")
    parser.add_argument(
        "--output-dir",
        default="price_data",
        help="Directory to store per-item JSON files (default: ./price_data)",
    )
    args = parser.parse_args()

    try:
        stats = process_pdf(args.pdf_path, args.output_dir)
    except ValueError as e:
        print(f"Error: {e}", file=sys.stderr)
        sys.exit(1)

    print(f"Date: {stats['date']}")
    print(f"Items processed: {stats['total']} ({stats['with_data']} with price data)")
    for w in stats["warnings"]:
        print(f"Warning: {w}")
    print(f"JSON files written to: {stats['output_dir']}")


if __name__ == "__main__":
    main()
