-- ==============================================================================
-- Migration: Sri Lanka Rupee Inflation & Macroeconomic Indicators Table
-- Date: 2026-10-06
--
-- Features:
-- - Tracks Headline Colombo Consumer Price Index (CCPI) & National CPI (NCPI)
-- - Tracks Food Inflation YoY & MoM (primary driver of agricultural pricing)
-- - Tracks Core Inflation and USD/LKR Central Bank Exchange Rates
-- - Supports Multi-Granularity: 'monthly', 'yearly', 'weekly', and 'daily'
-- - Full Row Level Security (RLS) with public read access
-- ==============================================================================

CREATE TABLE IF NOT EXISTS public.inflation_rates (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    date DATE NOT NULL,
    year INT NOT NULL,
    month INT,
    period_type TEXT NOT NULL DEFAULT 'monthly' 
        CHECK (period_type IN ('daily', 'weekly', 'monthly', 'yearly')),
    
    -- Headline Colombo Consumer Price Index (CCPI - 2021=100 / 2013=100)
    ccpi_index NUMERIC,
    ccpi_yoy_inflation NUMERIC,       -- Headline Inflation Rate (Year-on-Year %)
    ccpi_mom_inflation NUMERIC,       -- Month-on-Month % change
    
    -- Food Inflation (Direct correlation with agricultural market commodities)
    food_inflation_yoy NUMERIC,       -- Food Inflation Rate (Year-on-Year %)
    food_inflation_mom NUMERIC,       -- Food Month-on-Month % change
    
    -- Core Inflation (Excluding volatile food and energy)
    core_inflation_yoy NUMERIC,
    
    -- National Consumer Price Index (NCPI - Islandwide)
    ncpi_index NUMERIC,
    ncpi_yoy_inflation NUMERIC,
    ncpi_food_inflation_yoy NUMERIC,
    
    -- Currency Valuation & Exchange Rate (Rupee Value)
    usd_lkr_rate NUMERIC,             -- Central Bank USD/LKR Middle/Indicative Rate
    
    source TEXT NOT NULL DEFAULT 'cbsl' 
        CHECK (source IN ('cbsl', 'dcs', 'world_bank', 'imf', 'calculated')),
    notes TEXT,
    created_at TIMESTAMPTZ DEFAULT NOW(),
    
    CONSTRAINT unique_inflation_entry UNIQUE (date, period_type)
);

-- Indexes for Fast Analytics & Time-Series Graphing
CREATE INDEX IF NOT EXISTS idx_inflation_date ON public.inflation_rates (date DESC);
CREATE INDEX IF NOT EXISTS idx_inflation_period ON public.inflation_rates (period_type, date DESC);
CREATE INDEX IF NOT EXISTS idx_inflation_year ON public.inflation_rates (year, month);

-- Enable Row Level Security (RLS)
ALTER TABLE public.inflation_rates ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Public inflation rates are viewable by everyone" 
    ON public.inflation_rates FOR SELECT USING (true);

CREATE POLICY "Service role full access on inflation rates" 
    ON public.inflation_rates FOR ALL USING (true) WITH CHECK (true);
