-- ==============================================================================
-- Migration: Rolling 1-Year Sri Lanka Inflation & Rupee Forecasts Table
-- Date: 2026-10-06
--
-- Features:
-- - Stores rolling forward-looking 365-day prediction window
-- - Prunes expired predictions (forecast_date <= CURRENT_DATE) on each sync run
-- - Tracks Headline CCPI, Food Inflation, Core Inflation, and USD/LKR exchange rate
-- - Includes statistical confidence intervals (80% uncertainty bounds)
-- - Enables public read access via Row Level Security (RLS)
-- ==============================================================================

CREATE TABLE IF NOT EXISTS public.inflation_forecasts (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    forecast_date DATE NOT NULL,
    target_year INT NOT NULL,
    target_month INT NOT NULL,
    period_type TEXT NOT NULL DEFAULT 'daily' 
        CHECK (period_type IN ('daily', 'monthly')),
    
    -- Predicted Macroeconomic Metrics
    predicted_ccpi_yoy NUMERIC NOT NULL,     -- Predicted Headline CCPI (Year-on-Year %)
    predicted_food_yoy NUMERIC NOT NULL,     -- Predicted Food Inflation (Year-on-Year %)
    predicted_core_yoy NUMERIC,              -- Predicted Core Inflation (Year-on-Year %)
    predicted_usd_lkr NUMERIC NOT NULL,      -- Predicted USD/LKR Exchange Rate
    
    -- Uncertainty Bounds (80% Confidence Interval)
    confidence_lower NUMERIC,                -- Lower bound of CCPI prediction
    confidence_upper NUMERIC,                -- Upper bound of CCPI prediction
    
    model_name TEXT NOT NULL DEFAULT 'rolling_time_series_v1',
    generated_at TIMESTAMPTZ DEFAULT NOW(),
    
    CONSTRAINT unique_forecast UNIQUE (forecast_date, period_type)
);

-- Indexes for Fast Time-Series Querying
CREATE INDEX IF NOT EXISTS idx_forecast_date ON public.inflation_forecasts (forecast_date ASC);
CREATE INDEX IF NOT EXISTS idx_forecast_period ON public.inflation_forecasts (period_type, forecast_date ASC);

-- Enable Row Level Security (RLS)
ALTER TABLE public.inflation_forecasts ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Public inflation forecasts are viewable by everyone" 
    ON public.inflation_forecasts FOR SELECT USING (true);

CREATE POLICY "Service role full access on inflation forecasts" 
    ON public.inflation_forecasts FOR ALL USING (true) WITH CHECK (true);
