-- ==============================================================================
-- NAMIS (NATIONAL AGRICULTURAL MARKET INFORMATION SYSTEM)
-- PROFESSIONAL PRODUCTION DATABASE SCHEMA & INITIALIZATION
-- Project: Agriculture Market (https://lszuxjqlnjatqnnyuqda.supabase.co)
-- ==============================================================================
-- Instructions:
-- 1. Open your Supabase Dashboard -> Project "Agriculture Market"
-- 2. Go to SQL Editor -> New Query
-- 3. Paste this ENTIRE script and click "RUN"
-- ==============================================================================

-- 1. EXTENSIONS
CREATE EXTENSION IF NOT EXISTS "uuid-ossp";

-- 2. CORE REFERENCE TABLES

-- CATEGORIES
CREATE TABLE IF NOT EXISTS public.categories (
    id TEXT PRIMARY KEY,
    name TEXT NOT NULL,
    name_si TEXT DEFAULT '',
    emoji TEXT DEFAULT '📁',
    created_at TIMESTAMPTZ DEFAULT NOW()
);

-- MARKETS (12 Canonical National Economic Centres & Wholesale Hubs)
CREATE TABLE IF NOT EXISTS public.markets (
    id TEXT PRIMARY KEY,
    name TEXT NOT NULL,
    name_si TEXT DEFAULT '',
    district TEXT DEFAULT '',
    province TEXT DEFAULT '',
    emoji TEXT DEFAULT '🏢',
    is_active BOOLEAN DEFAULT true,
    created_at TIMESTAMPTZ DEFAULT NOW()
);

-- VEGETABLES & COMMODITIES (Cleaned Canonical Items with SVG Icons)
CREATE TABLE IF NOT EXISTS public.vegetables (
    id TEXT PRIMARY KEY,
    category_id TEXT NOT NULL REFERENCES public.categories(id) ON DELETE CASCADE,
    name TEXT NOT NULL,
    name_si TEXT DEFAULT '',
    emoji TEXT DEFAULT '🥬',
    icon_url TEXT,
    unit TEXT DEFAULT 'kg',
    min_price NUMERIC,
    max_price NUMERIC,
    created_at TIMESTAMPTZ DEFAULT NOW()
);

-- 3. UNIFIED TIME-SERIES PRICE ENTRIES
CREATE TABLE IF NOT EXISTS public.price_entries (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    market_id TEXT NOT NULL REFERENCES public.markets(id) ON DELETE CASCADE,
    vegetable_id TEXT NOT NULL REFERENCES public.vegetables(id) ON DELETE CASCADE,
    price NUMERIC NOT NULL,
    min_price NUMERIC,
    max_price NUMERIC,
    price_type TEXT NOT NULL DEFAULT 'wholesale' CHECK (price_type IN ('wholesale', 'retail')),
    source TEXT NOT NULL DEFAULT 'harti' CHECK (source IN ('harti', 'dambulla_dec', 'cbsl', 'dcs_retail', 'manual')),
    date DATE NOT NULL,
    note TEXT,
    created_at TIMESTAMPTZ DEFAULT NOW(),
    updated_at TIMESTAMPTZ DEFAULT NOW(),
    CONSTRAINT unique_price_entry UNIQUE (vegetable_id, market_id, date, price_type)
);

-- Ultra-Fast Query Indexes
CREATE INDEX IF NOT EXISTS idx_price_entries_date ON public.price_entries (date DESC);
CREATE INDEX IF NOT EXISTS idx_price_entries_market_date ON public.price_entries (market_id, date DESC);
CREATE INDEX IF NOT EXISTS idx_price_entries_veg_date ON public.price_entries (vegetable_id, date DESC);
CREATE INDEX IF NOT EXISTS idx_price_entries_type_date ON public.price_entries (price_type, date DESC);
CREATE INDEX IF NOT EXISTS idx_price_entries_lookup ON public.price_entries (vegetable_id, market_id, date, price_type);

-- 4. MARKET CALENDAR & HOLIDAYS (Essential for ML model training)
CREATE TABLE IF NOT EXISTS public.market_calendar (
    date DATE PRIMARY KEY,
    is_trading_day BOOLEAN NOT NULL DEFAULT true,
    day_of_week TEXT NOT NULL,
    closure_reason TEXT,
    holiday_name TEXT,
    notes TEXT,
    created_at TIMESTAMPTZ DEFAULT NOW()
);

CREATE INDEX IF NOT EXISTS idx_market_calendar_trading ON public.market_calendar (is_trading_day);

-- 5. SPECIALIZED MULTI-SOURCE BENCHMARK TABLES

-- RETAIL CONSUMER DASHBOARD (DCS Colombo District 14 Markets)
CREATE TABLE IF NOT EXISTS public.retail_price_entries (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    commodity_code TEXT NOT NULL,
    commodity_name TEXT NOT NULL,
    category TEXT NOT NULL,
    price NUMERIC NOT NULL,
    date_label TEXT NOT NULL,
    parsed_date DATE,
    created_at TIMESTAMPTZ DEFAULT NOW(),
    CONSTRAINT unique_retail_price UNIQUE (commodity_code, date_label)
);

CREATE INDEX IF NOT EXISTS idx_retail_prices_date ON public.retail_price_entries (parsed_date DESC);
CREATE INDEX IF NOT EXISTS idx_retail_prices_code ON public.retail_price_entries (commodity_code);

-- CENTRAL BANK OF SRI LANKA (CBSL Daily Price Reports)
CREATE TABLE IF NOT EXISTS public.cbsl_price_entries (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    date DATE NOT NULL,
    item_name TEXT NOT NULL,
    category TEXT NOT NULL,
    pettah_wholesale NUMERIC,
    pettah_retail NUMERIC,
    dambulla_wholesale NUMERIC,
    narahenpita_retail NUMERIC,
    created_at TIMESTAMPTZ DEFAULT NOW(),
    CONSTRAINT unique_cbsl_entry UNIQUE (date, item_name)
);

CREATE INDEX IF NOT EXISTS idx_cbsl_prices_date ON public.cbsl_price_entries (date DESC);

-- 6. SYSTEM ADMINISTRATION & SUPPORT TABLES

CREATE TABLE IF NOT EXISTS public.admins (
    id TEXT PRIMARY KEY,
    email TEXT UNIQUE NOT NULL,
    password_hash TEXT NOT NULL,
    name TEXT NOT NULL,
    role TEXT DEFAULT 'viewer',
    market_id TEXT REFERENCES public.markets(id) ON DELETE SET NULL,
    is_active BOOLEAN DEFAULT true,
    last_login TIMESTAMPTZ,
    created_at TIMESTAMPTZ DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS public.contact_messages (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    full_name TEXT NOT NULL,
    email TEXT NOT NULL,
    phone TEXT,
    subject TEXT NOT NULL,
    message TEXT NOT NULL,
    is_read BOOLEAN DEFAULT false,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS public.support_tickets (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    ticket_id TEXT UNIQUE NOT NULL,
    phone_or_email TEXT NOT NULL,
    category TEXT NOT NULL,
    subject TEXT NOT NULL,
    priority TEXT NOT NULL DEFAULT 'medium',
    status TEXT NOT NULL DEFAULT 'open',
    description TEXT NOT NULL,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

-- ==============================================================================
-- 7. CLEAN PRODUCTION REFERENCE SEED DATA
-- ==============================================================================

-- SEED CATEGORIES (13 Clean Categories)
INSERT INTO public.categories (id, name, name_si, emoji) VALUES
('up-country-vegetable', 'Up Country Vegetable', 'උඩරට එළවළු', '🥕'),
('low-country-vegetable', 'Low country Vegetable', 'පහතරට එළවළු', '🥒'),
('rice', 'Rice', 'සහල්', '🌾'),
('imported-rice', 'Imported Rice', 'ආනයනික සහල්', '🍚'),
('potatoes', 'Potatoes', 'අර්තාපල්', '🥔'),
('onion', 'Onion', 'ළූණු', '🧅'),
('big-onion', 'Big Onion', 'ලොකු ළූණු', '🧅'),
('pulses', 'Pulses', 'ධාන්‍ය / පරිප්පු', '🌾'),
('banana', 'Banana', 'කෙසෙල්', '🍌'),
('other-fruits--rs-fruit-', 'Other Fruits (Rs/Fruit)', 'වෙනත් පලතුරු', '🍎'),
('dried-chillies', 'Dried Chillies', 'වියළි මිරිස්', '🌶️'),
('eggs', 'Eggs', 'බිත්තර', '🥚'),
('consumption-item', 'Consumption Item', 'පාරිභෝගික භාණ්ඩ', '🛒')
ON CONFLICT (id) DO UPDATE SET name = EXCLUDED.name, emoji = EXCLUDED.emoji;

-- SEED MARKETS (12 Canonical Markets - Peliyagod merged into Peliyagoda)
INSERT INTO public.markets (id, name, name_si, district, province, emoji) VALUES
('bandarawela', 'Bandarawela Economic Center', 'බණ්ඩාරවෙල ආර්ථික මධ්‍යස්ථානය', 'Badulla', 'Uva', '🏢'),
('dambulla', 'Dambulla Economic Center', 'දඹුල්ල ආර්ථික මධ්‍යස්ථානය', 'Matale', 'Central', '🏢'),
('kandy', 'Kandy Central Market', 'මහනුවර වෙළෙඳපොළ', 'Kandy', 'Central', '🏢'),
('keppetipola', 'Keppetipola Economic Center', 'කැප්පෙටිපොළ ආර්ථික මධ්‍යස්ථානය', 'Badulla', 'Uva', '🏢'),
('manning', 'Manning Market (Peliyagoda)', 'මැනිං වෙළෙඳපොළ', 'Colombo', 'Western', '🏢'),
('meegoda', 'Meegoda Economic Center', 'මීගොඩ ආර්ථික මධ්‍යස්ථානය', 'Colombo', 'Western', '🏢'),
('norochchole', 'Norochchole Economic Center', 'නොරොච්චෝලේ ආර්ථික මධ්‍යස්ථානය', 'Puttalam', 'North Western', '🏢'),
('nuwara-eliya', 'Nuwara Eliya Economic Center', 'නුවරඑළිය ආර්ථික මධ්‍යස්ථානය', 'Nuwara Eliya', 'Central', '🏢'),
('peliyagoda', 'Peliyagoda Economic Center', 'පෑලියගොඩ ආර්ථික මධ්‍යස්ථානය', 'Gampaha', 'Western', '🏢'),
('pettah', 'Pettah Wholesale Market', 'පිටකොටුව තොග වෙළෙඳපොළ', 'Colombo', 'Western', '🏢'),
('thambuththegama', 'Thambuththegama Economic Center', 'තඹුත්තේගම ආර්ථික මධ්‍යස්ථානය', 'Anuradhapura', 'North Central', '🏢'),
('veyangoda', 'Veyangoda Economic Center', 'වේයන්ගොඩ ආර්ථික මධ්‍යස්ථානය', 'Gampaha', 'Western', '🏢')
ON CONFLICT (id) DO UPDATE SET name = EXCLUDED.name, district = EXCLUDED.district, province = EXCLUDED.province;

-- SEED VEGETABLES (Cleaned of all Excel corruption, with real SVG icon paths)
INSERT INTO public.vegetables (id, category_id, name, name_si, emoji, icon_url, unit) VALUES
-- Up Country Vegetables
('beans', 'up-country-vegetable', 'Beans', 'බෝංචි', '🥬', '/icons/broad-bean/broad-bean.svg', 'kg'),
('beet-root', 'up-country-vegetable', 'Beet root', 'බීට්රූට්', '🥔', '/icons/beet/beet.svg', 'kg'),
('cabbage--kandy-', 'up-country-vegetable', 'Cabbage (Kandy)', 'ගෝවා (මහනුවර)', '🥬', '/icons/green-cabbage/green-cabbage.svg', 'kg'),
('carrot', 'up-country-vegetable', 'Carrot', 'කැරට්', '🥕', '/icons/carrot/carrot.svg', 'kg'),
('knolkhol', 'up-country-vegetable', 'Knolkhol', 'නෝකෝල්', '🥬', '/icons/kohlrabi/kohlrabi.svg', 'kg'),
('leeks', 'up-country-vegetable', 'Leeks', 'ලීක්ස්', '🥬', '/icons/leek/leek.svg', 'kg'),
('raddish', 'up-country-vegetable', 'Raddish', 'රාබු', '🥕', '/icons/cherry-bell-radish/cherry-bell-radish.svg', 'kg'),
('tomato', 'up-country-vegetable', 'Tomato', 'තක්කාලි', '🍅', '/icons/tomato/tomato.svg', 'kg'),

-- Low Country Vegetables
('ash-plantains', 'low-country-vegetable', 'Ash Plantains', 'අළු කෙසෙල්', '🍌', '/icons/plantain/plantain.svg', 'kg'),
('bitter-gourd', 'low-country-vegetable', 'Bitter Gourd', 'කරවිල', '🥒', '/icons/butternut-squash/butternut-squash.svg', 'kg'),
('brinjals', 'low-country-vegetable', 'Brinjals', 'වම්බටු', '🍆', '/icons/eggplant/eggplant.svg', 'kg'),
('capsicum', 'low-country-vegetable', 'Capsicum', 'මාළු මිරිස්', '🫑', '/icons/green-bell-pepper/green-bell-pepper.svg', 'kg'),
('cucumber', 'low-country-vegetable', 'Cucumber', 'පිපිඤ්ඤා', '🥒', '/icons/cucumber/cucumber.svg', 'kg'),
('drumstick', 'low-country-vegetable', 'Drumstick', 'මුරුංගා', '🥖', '/icons/generic-plant/generic-plant.svg', 'kg'),
('green-chillies', 'low-country-vegetable', 'Green Chillies', 'අමු මිරිස්', '🌶️', '/icons/birds-eye-chili/birds-eye-chili.svg', 'kg'),
('ladies-fingers', 'low-country-vegetable', 'Ladies Fingers', 'බණ්ඩක්කා', '🥬', '/icons/okra/okra.svg', 'kg'),
('lime', 'low-country-vegetable', 'Lime', 'දෙහි', '🍋', '/icons/generic-apple/generic-apple.svg', 'kg'),
('long-beans', 'low-country-vegetable', 'Long Beans', 'මෑකරල්', '🥬', '/icons/broad-bean/broad-bean.svg', 'kg'),
('luffa', 'low-country-vegetable', 'Luffa', 'වැටකොළු', '🥒', '/icons/zucchini/zucchini.svg', 'kg'),
('manioc', 'low-country-vegetable', 'Manioc', 'මඤ්ඤොක්කා', '🥔', '/icons/japanese-yam/japanese-yam.svg', 'kg'),
('pumpkin', 'low-country-vegetable', 'Pumpkin', 'වට්ටක්කා', '🎃', '/icons/pumpkin/pumpkin.svg', 'kg'),
('snake-gourd', 'low-country-vegetable', 'Snake Gourd', 'පතෝල', '🥒', '/icons/zucchini/zucchini.svg', 'kg'),
('sweet-potatoe', 'low-country-vegetable', 'Sweet Potatoe', 'බතල', '🥔', '/icons/sweet-potato/sweet-potato.svg', 'kg'),

-- Potatoes
('potato--imported-', 'potatoes', 'Potato (Imported)', 'ආනයනික අර්තාපල්', '🥔', '/icons/russet-potato/russet-potato.svg', 'kg'),
('potato--nuwaraeliya-', 'potatoes', 'Potato (Nuwaraeliya)', 'නුවරඑළිය අර්තාපල්', '🥔', '/icons/russet-potato/russet-potato.svg', 'kg'),
('potato--welimada-', 'potatoes', 'Potato (Welimada)', 'වැලිමඩ අර්තාපල්', '🥔', '/icons/russet-potato/russet-potato.svg', 'kg'),

-- Onions
('imported', 'big-onion', 'Big Onion (Imported)', 'ආනයනික ලොකු ළූණු', '🧅', '/icons/yellow-onion/yellow-onion.svg', 'kg'),
('sinnan', 'onion', 'Red Onion (Sinnan)', 'සින්නන් ළූණු', '🧅', '/icons/red-onion/red-onion.svg', 'Rs/Kg'),
('vedalan', 'onion', 'Red Onion (Vedalan)', 'වෙදලන් ළූණු', '🧅', '/icons/red-onion/red-onion.svg', 'Rs/Kg'),

-- Fruits & Bananas
('ambul', 'banana', 'Ambul Banana', 'ඇඹුල් කෙසෙල්', '🍌', '/icons/plantain/plantain.svg', 'kg'),
('anamalu--rs-fruits-', 'banana', 'Anamalu Banana', 'ආනමාලු', '🍌', '/icons/plantain/plantain.svg', 'Rs/Fruit'),
('kolikuttu', 'banana', 'Kolikuttu Banana', 'කෝලිකුට්ටු', '🍌', '/icons/plantain/plantain.svg', 'kg'),
('seeni', 'banana', 'Seeni Banana', 'සීනි කෙසෙල්', '🍌', '/icons/plantain/plantain.svg', 'kg'),
('papaya', 'other-fruits--rs-fruit-', 'Papaya', 'පැපොල්', '🍈', '/icons/generic-melon/generic-melon.svg', 'kg'),
('pineapple---large', 'other-fruits--rs-fruit-', 'Pineapple (Large)', 'අන්නාසි (විශාල)', '🍍', '/icons/pineapple-tomato/pineapple-tomato.svg', 'kg'),
('pineapple---medium', 'other-fruits--rs-fruit-', 'Pineapple (Medium)', 'අන්නාසි (මධ්‍යම)', '🍍', '/icons/pineapple-tomato/pineapple-tomato.svg', 'kg'),
('avocado', 'other-fruits--rs-fruit-', 'Avocado', 'අලිගැටපේර', '🥑', '/icons/generic-apple/generic-apple.svg', 'kg'),
('passion-fruits', 'other-fruits--rs-fruit-', 'Passion Fruits', 'පැෂන් ෆෘට්', '🍈', '/icons/generic-apple/generic-apple.svg', 'kg'),
('woodapple', 'other-fruits--rs-fruit-', 'Woodapple', 'දිවුල්', '🥥', '/icons/generic-apple/generic-apple.svg', 'kg'),

-- Rice (Local & Imported)
('keeri-samba', 'rice', 'Keeri Samba', 'කීරි සම්බා', '🍚', '/icons/rice/rice.svg', 'Rs/kg'),
('nadu', 'rice', 'Nadu', 'නාඩු', '🍚', '/icons/rice/rice.svg', 'Rs/kg'),
('raw-red', 'rice', 'Raw red', 'රතු කැකුළු', '🍚', '/icons/rice/rice.svg', 'Rs/kg'),
('raw-white', 'imported-rice', 'Raw White', 'කැකුළු සුදු', '🍚', '/icons/rice/rice.svg', 'kg'),
('samba-1', 'rice', 'Samba 1', 'සම්බා 1', '🍚', '/icons/rice/rice.svg', 'Rs/kg'),
('samba-2', 'rice', 'Samba 2', 'සම්බා 2', '🍚', '/icons/rice/rice.svg', 'Rs/kg'),
('ponne-samba', 'imported-rice', 'Ponne Samba', 'පොන්නි සම්බා', '🍚', '/icons/rice/rice.svg', 'kg'),

-- Pulses & Grains
('red-dhal', 'pulses', 'Red Dhal (Mysore)', 'මයිසූර් පරිප්පු', '🌾', '/icons/soy-bean/soy-bean.svg', 'Rs/Kg'),
('green-gram', 'pulses', 'Green Gram', 'මුං ඇට', '🌾', '/icons/soy-bean/soy-bean.svg', 'Rs/Kg'),
('cowpea', 'pulses', 'Cowpea', 'කවුපි', '🌾', '/icons/soy-bean/soy-bean.svg', 'Rs/Kg'),
('black-gram', 'pulses', 'Black Gram', 'උඳු', '🌾', '/icons/soy-bean/soy-bean.svg', 'kg'),

-- Consumption Items & Eggs
('sugar-white-', 'consumption-item', 'Sugar (White)', 'සුදු සීනි', '🍚', '/icons/sugar-cane/sugar-cane.svg', 'Rs/Kg'),
('wheat-flour', 'consumption-item', 'Wheat Flour', 'තිරිඟු පිටි', '🌾', '/icons/wheat/wheat.svg', 'Rs/Kg'),
('white', 'eggs', 'Eggs (White)', 'සුදු බිත්තර', '🥚', '/icons/generic-plant/generic-plant.svg', 'Rs/Egg'),
('brown', 'eggs', 'Eggs (Brown)', 'දුඹුරු බිත්තර', '🥚', '/icons/generic-plant/generic-plant.svg', 'Rs/Egg')
ON CONFLICT (id) DO UPDATE SET 
    name = EXCLUDED.name, 
    emoji = EXCLUDED.emoji, 
    icon_url = EXCLUDED.icon_url,
    unit = EXCLUDED.unit;

-- ==============================================================================
-- 8. ROW LEVEL SECURITY (RLS) POLICIES
-- ==============================================================================
ALTER TABLE public.categories ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.markets ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.vegetables ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.price_entries ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.market_calendar ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.retail_price_entries ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.cbsl_price_entries ENABLE ROW LEVEL SECURITY;

DO $$ BEGIN
    IF NOT EXISTS (SELECT 1 FROM pg_policies WHERE policyname = 'Public categories are viewable by everyone' AND tablename = 'categories') THEN
        CREATE POLICY "Public categories are viewable by everyone" ON public.categories FOR SELECT USING (true);
    END IF;
    IF NOT EXISTS (SELECT 1 FROM pg_policies WHERE policyname = 'Public markets are viewable by everyone' AND tablename = 'markets') THEN
        CREATE POLICY "Public markets are viewable by everyone" ON public.markets FOR SELECT USING (true);
    END IF;
    IF NOT EXISTS (SELECT 1 FROM pg_policies WHERE policyname = 'Public vegetables are viewable by everyone' AND tablename = 'vegetables') THEN
        CREATE POLICY "Public vegetables are viewable by everyone" ON public.vegetables FOR SELECT USING (true);
    END IF;
    IF NOT EXISTS (SELECT 1 FROM pg_policies WHERE policyname = 'Public price entries are viewable by everyone' AND tablename = 'price_entries') THEN
        CREATE POLICY "Public price entries are viewable by everyone" ON public.price_entries FOR SELECT USING (true);
    END IF;
    IF NOT EXISTS (SELECT 1 FROM pg_policies WHERE policyname = 'Public market calendar is viewable by everyone' AND tablename = 'market_calendar') THEN
        CREATE POLICY "Public market calendar is viewable by everyone" ON public.market_calendar FOR SELECT USING (true);
    END IF;
    IF NOT EXISTS (SELECT 1 FROM pg_policies WHERE policyname = 'Public retail price entries are viewable by everyone' AND tablename = 'retail_price_entries') THEN
        CREATE POLICY "Public retail price entries are viewable by everyone" ON public.retail_price_entries FOR SELECT USING (true);
    END IF;
    IF NOT EXISTS (SELECT 1 FROM pg_policies WHERE policyname = 'Public cbsl price entries are viewable by everyone' AND tablename = 'cbsl_price_entries') THEN
        CREATE POLICY "Public cbsl price entries are viewable by everyone" ON public.cbsl_price_entries FOR SELECT USING (true);
    END IF;
END $$;
